#!/bin/python3

import math
import os
import random
import re
import sys
#
# Complete the 'missingCharacters' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def missingCharacters(s):
    # Write your code here
    present_chars = set(s)
    
    result = []
    
    all_digits = "0123456789"
    for d in all_digits:
        if d not in present_chars:
            result.append(d)
    
    
    all_letters = "abcdefghijklmnopqrstuvwxyz"
    for char in all_letters:
        if char not in present_chars:
            result.append(char)
    
    return "".join(result)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = missingCharacters(s)

    fptr.write(result + '\n')

    fptr.close()
